name: CI

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - name: Install Node to GitHub Actions functionality
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install project pnpm dependencies
        run: pnpm install --frozen-lockfile

      - name: Set SHAs for "nx affected" commands
        uses: nrwl/nx-set-shas@v4

      - name: Install luabundler
        run: pnpm install -g luabundler

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - name: Perform nx affected tests
        run: pnpm exec nx affected -t lint test build --exclude func-runner

      # For build artifacts which need publicly accessible links, individual steps should be used!

      - name: 'Upload build artifact: Importer'
        uses: actions/upload-artifact@v4
        with:
          name: dist-importer
          path: |
            ${{ github.workspace }}/dist/packages/tts-mtg-importer/bundle.lua
          if-no-files-found: error
          include-hidden-files: true
